language: ruby
branches:
  only:
  - master
install: true
script:
- "./do build"
deploy:
  skip_cleanup: true
  provider: script
  script: "./do deploy"
env:
  global:
  - secure: FmzcFqUumrbJP0V5CmWNZ7+8DHMeGIcERMiFsaT4Sk9LUtN6TkRwUJMGhLGcpJZbkEGsfcaJ6v9/QdNJgb26OhOTCtew8qgoy5R9uymtn96CCqRbTr/zHgVgq/nE3F4ZTCKA0rNaqBFo+Jm6S2a+L4MChjX0YfZ+7+fYnuPUebtPfYtGvvvs+tVXr8m4b/v+ctVhuAmV5CuHmYWknxf70Dsm4JvHZoaTDSE12Bm5N9MWtf4KNaH7dKlyZ0Ejdwi9cNLmbPD9cnObEtgJw0fhQ2MKWuDzcQeeY4n4zFyfO6/I4vxYyPFaP0kpABGxWh5biVZ/EzGTcL/QYXfHNYmCrZEf88VuWDAPTiBtwT1899SQhEsVp7kYqMbrmUze78IrXx902y/IhJPtFTG7G4AP6ncDdql0/sbRo9BxMgSO41IkO1J2ZRrZTWvuBxFZ0Ld8p1Rij9eiKvG9QTUPENpPxC9xW6UOPvECmMqtW59OTcUgiefDL49e2f2HkQv3l823NgoZpHhRzAGh3wDgnwGoYx60/1XJP6lwe77I3GqU7ZJ2OD3yHRI+XOEBUnz4jUaUj8oQ8TNJnGEAqi/z4SAVrgQzW7tFSl0kUpqFe15axdwhYvCVeHg4gx/E76VpFSEdVVFeUMGUi199lj470fh9edoM0iuU+utRJMHc8GkZ6PI=
  - secure: i+LyD+eUH30ZW80aIJBjZpWVir9FU9z1bZTL1kruI2p8S1xr36JStDTP/r4jLk929OxB+AQauGcmvlOfXaRH6flUdIEC9Hf5YhFGYRpAX4y0qXzlr7C1Kzlk0UccKhzu4uwJYHZsgfFrkp9Ry4MVnVOZszknnZZQ0YKPEzjVh/+PnoD5kpzIRffRTMY7qBDN+tVCMmQSa0bbgPI/jJfI9xlt8OxwWZuEkkLEfEXpLhdZ1emAycRbFrJYKcdfYxX+rZRhjRYaMKB+/oXUdqMVce0Ll3xNoOiswPwVaTO1F09YL/m5GjUDJJ5JozqXPIZIoj+cUyEZTM5gdUi1PzsKU3wx8o/T+//nVEsWDjUoO7HDw5D3aZhhMGz7rJ0Ggf4NB33EwMi6kneBD4aVyftK58SuUu4+7YyfEt8zXiho0z+feIGxSt/qPRSu8Mznh5D9bhkR59oX4VwaJgmc6G1r3/T+Dxf+UExAR1hfu5DJ0kTXQ4tHqhrWjPTkpmp0IaF+YcVQKQyTJBbuCOFUy8NyaCSDkp0sG8r7J+zrr0liPp1yuX25ko0YOrIWUU6KW+6cvMrx5OpCYsFkQqVl1zrh0/UO3SukPciwEVF/Oooqqwd+qdPMUptw9G5napbVzKwQt2JDossVIU3Y7yZmZ/deJkVNCjnEsthkavxLguJtgoc=
